#!/bin/sh

now="  Desktop"
win="类  Window"
area="麗  Selection"

options="$now\n$win\n$area"

chosen="$(echo "$options" | dmenu -c -l 10 -i -bw 3 -F -h 35)"

case "$chosen" in
  "$now")
    takeshot now
    ;;
  "$win")
    takeshot win
    ;;
  "$area")
    takeshot area
    ;;
esac
