#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Start removable disk automounter
udiskie &

# Launch notification daemon
dunst -config "$HOME/.config/dunstrc" &

# Start polybar
# "$HOME"/.config/polybar/launch.sh &

# Resolution
xrandr -s 2560x1080 &

# Compositor
picom --config "$HOME"/.config/picom.conf &

[ -x "$(command -v playerctld)" ] && playerctld daemon

# Restore wallpaper
if [ -f ~/.fehbg ]; then
	~/.fehbg &
fi

# Start hotkey demon
# sxhkd &

# Start dwmblocks
dwmblocks &

# Set keyboard layout and remap capslock to ctrl
setxkbmap -layout pl -option ctrl:nocaps &

# Start dwm
exec dwm

# exec bspwm
