#!/usr/bin/env bash

# Restore wallpaper
bash "$HOME/.config/bspwm/.fehbg"

pgrep -x sxhkd > /dev/null || sxhkd &
"$HOME"/.config/polybar/launch.sh

# bspc monitor -d '' '' '' '' '' '' '' '' '' '' '漣' ''
# bspc monitor -d 'www' 'dev1' 'dev2' 'dev3' 'dev4' 'chat' 'doc' 'media' 'sys' 'vbox'
bspc monitor -d '' '' '' '' '' '' '' '' '' ''

bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.6

bspc config top_padding 35

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

declare -a web=(firefox brave Brave google-chrome)
for i in "${web[@]}"; do
  bspc rule -a "$i" desktop='^1' follow=on focus=on
done

declare -a communicator=(Slack)
for i in "${communicator[@]}"; do
  bspc rule -a "$i" desktop='^6' follow=on focus=on
done

declare -a docs=(Thunar Joplin)
for i in "${docs[@]}"; do
  bspc rule -a "$i" desktop='^7' follow=on focus=on
done

declare -a settings=(gimp)
for i in "${settings[@]}"; do
  bspc rule -a "$i" desktop='^9' follow=on focus=on
done

declare -a vbox=("VirtualBox Manager")
for i in "${vbox[@]}"; do
  bspc rule -a "$i" desktop='^0' follow=on focus=on
done

declare -a floats=(1Password Viewmonitor GParted Appearance \
Pavucontrol Xfce4-settings-manager)
for i in "${floats[@]}"; do
  bspc rule -a "$i" state=floating center=on follow=on focus=on
done

## Set layouts
# if command -v bsp-layout &> /dev/null
# then
#   bsp-layout set tall  --master-size=0.6
#   bsp-layout set tall  --master-size=0.6
# fi

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey eww playerctld

# Launch notification daemon
dunst -config "$HOME/.config/bspwm/dunstrc" &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Map Caps-Lock key to Ctrl
setxkbmap -option ctrl:nocaps

# polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Start udiskie
udiskie &

# start playerctld
playerctld daemon

# start compositor
while pgrep -u "$UID" -x picom >/dev/null; do sleep 1; done
picom --config "$HOME/.config/bspwm/picom.conf" &

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/tokyo-night "$XFCE_TERM_PATH"/terminalrc
