#! /bin/sh

# Restore wallpaper
bash $HOME/.config/bspwm/.fehbg

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d '' '' '' '' '' '' '' '' '' '' '漣' ''

bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.50

bspc config top_padding 35

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# workspace 1 (Terminals)
# declare -a terminal=(Alacritty Xfce4-terminal)
# for i in ${terminal[@]}; do
#     bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(firefox discord)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar Pcmanfm qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a office=(Code Geany Joplin)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^8' follow=on focus=on; done

# workspace 5 (Communication)
declare -a communicator=(Slack)
for i in ${communicator[@]}; do
    bspc rule -a $i desktop='^9' follow=on focus=on; done

# workspace 6 (Media)
declare -a media=(spotify)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^0' follow=on focus=on; done

# workspace 7 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
Pavucontrol Xfce4-settings-manager)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^11' follow=on focus=on; done

# workspace 8 (Virtualization)
declare -a manager=("VirtualBox Manager")
for i in ${manager[@]}; do
    bspc rule -a $i desktop='^12' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a 1Password state=floating center=on follow=on focus=on

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey eww playerctld

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Start udiskie
udiskie &

# start playerctld
playerctld daemon

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/bspwm/picom.conf &

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/tokyo-night "$XFCE_TERM_PATH"/terminalrc
