#!/bin/bash

bspc monitor -d '' '' '' '' '' '' '' '' '' ''

bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.55

bspc config top_padding 35

bspc config focused_border_color  "#7aa2f7"
bspc config normal_border_color   "#32344a"
bspc config active_border_color   "#444b6a"

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        false
bspc config focus_follows_pointer false

xsetroot -cursor_name left_ptr

declare -a browsers=(firefox Brave-browser)
for i in "${browsers[@]}"; do
  bspc rule -a "$i" desktop='^1' follow=on focus=on
done

declare -a communicator=(Slack "Microsoft Teams - Preview")
for i in "${communicator[@]}"; do
  bspc rule -a "$i" desktop='^6'
done

declare -a docs=(Joplin)
for i in "${docs[@]}"; do
  bspc rule -a "$i" desktop='^7' follow=on focus=on
done

# Install aur/spotifywm-git
declare -a media=(Spotify)
for i in "${media[@]}"; do
  bspc rule -a "$i" desktop='^7'
done

declare -a design=(Gimp)
for i in "${design[@]}"; do
  bspc rule -a "$i" desktop='^9' follow=on focus=on
done

declare -a vbox=("VirtualBox Manager")
for i in "${vbox[@]}"; do
  bspc rule -a "$i" desktop='^0' follow=on focus=on
done

declare -a floats=(1Password Pavucontrol Sxiv Thunar)
for i in "${floats[@]}"; do
  bspc rule -a "$i" state=floating center=on follow=on focus=on
done
