XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"

typeset -U PATH path

path=("$HOME/.local/bin" "$path[@]")
export PATH

export PAGER=most
export TERMINAL=alacritty
export EDITOR=nvim
export BROWSER=brave

source "/home/morman/.rover/env"
