# export PROMPT='%B%F{blue}%2~ %f%b%# '

# Load version control information
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' formats '%fon %F{red} %b%f '

precmd() { vcs_info }

setopt prompt_subst

NEWLINE=$'\n'
PROMPT='${NEWLINE}%B%F{blue}%2~ ${vcs_info_msg_0_}${NEWLINE}%F{green}%f%b '

# Completions
autoload -Uz compinit
zstyle ':completion:*' menu select
compinit

# Enable history
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

autoload -Uz up-line-or-beginning-search down-line-or-beginning-search history-incremental-search-backward

bindkey '^R' history-incremental-search-backward

zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

[[ -n "${key[Up]}"   ]] && bindkey -- "${key[Up]}"   up-line-or-beginning-search
[[ -n "${key[Down]}" ]] && bindkey -- "${key[Down]}" down-line-or-beginning-search

# Load custom scripts
if [ -d ~/.config/zsh ]; then
  for f in ~/.config/zsh/* ; do
    . "$f"
  done

  unset f
fi

# Enable zoxide
[ -x "$(command -v zoxide)" ] && eval "$(zoxide init zsh)"

# Plugins

[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && . /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
