alias gst='git status'
alias glo='git log'
alias glr='git log -n 30'
alias ga='git add'
alias grbm='git rebase master'
alias grbim='git rebase -i master'
alias gci='git commit'
alias gbr='git branch'
alias gdi='git difftool'
alias gdiff='git difftool'
alias gd='git diff'
alias gco='git checkout'
alias gcm='git checkout master'
alias gp='git push'
alias gl='git pull'

alias ss='ruby -run -e httpd -- -p 5000 .'

alias be='bundle exec'

alias dotcode='code $DOTFILES'

alias tmux='tmux -2'
alias ts='tmux new -s (basename $PWD)'
alias tls='tmux ls'
